-- Batch 16/16 (final): Filipino-specific specialty items (35 items). Same
-- treatment as all prior batches — AI-estimated placeholders, honestly
-- tagged source='manual', verification_status='NEEDS_REVIEW', so the
-- "Ground from USDA" tool has real candidates to upgrade against, and any
-- item it can't confidently match still has usable (if approximate) data
-- rather than nulls blocking the meal-nutrition pipeline.
--
-- New food_group='Filipino Specialty' — items genuinely not covered by
-- any earlier, more generic batch: wrappers, native dairy, kakanin (rice
-- cakes), candies, street food, fermented/regional specialty condiments,
-- and a few base ingredients (quail eggs, carabao milk, pili nuts,
-- malagkit flour) that turned out to be missing entirely. Prepared/
-- street-food items (chicharon bulaklak, betamax, isaw, turon, kwek-kwek,
-- bagnet) are included as their own canonical rows following the same
-- precedent as Lechon kawali/Sisig/Fried rice in earlier batches — bought
-- and eaten as a single item, not decomposed into sub-ingredients.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Lumpia wrapper', 'Lumpia wrapper', array['lumpia wrapper', 'spring roll wrapper'], 'Wrapper', 'Filipino Specialty', 'raw', 'pantry',
   100, 'g', 280, 7, 58, 1, 0, 2, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', 10, 'sheet'),
  ('Siomai wrapper', 'Siomai wrapper (wonton wrapper)', array['siomai wrapper', 'wonton wrapper'], 'Wrapper', 'Filipino Specialty', 'raw', 'pantry',
   100, 'g', 280, 9, 55, 2, 0, 2, 450, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', 5, 'sheet'),
  ('Banana leaves', 'Banana leaves', array['dahon ng saging', 'banana leaves'], 'Leaf', 'Filipino Specialty', 'raw', 'pantry',
   100, 'g', 35, 2, 6, 0.5, 0, 3, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   30, 'kg', 'manual', 50, 'sheet'),
  ('Quail eggs, raw', 'Quail eggs', array['itlog na pugo', 'quail eggs'], 'Egg', 'Filipino Specialty', 'raw', 'main',
   100, 'g', 158, 13.1, 0.4, 11.1, 0.4, 0, 141, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', 10, 'egg'),
  ('Quail eggs, boiled', 'Boiled quail eggs', array['boiled pugo', 'boiled quail eggs'], 'Egg', 'Filipino Specialty', 'cooked', 'main',
   100, 'g', 170, 13.5, 0.6, 12.5, 0, 0, 145, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   280, 'kg', 'manual', 10, 'egg'),
  ('Carabao milk, raw', 'Carabao milk', array['gatas ng kalabaw', 'carabao milk', 'water buffalo milk'], 'Dairy', 'Filipino Specialty', 'raw', 'pantry',
   100, 'ml', 97, 4.3, 5.2, 6.9, 5.2, 0, 52, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Kesong puti', 'Kesong puti (carabao cheese)', array['kesong puti', 'carabao cheese', 'white cheese'], 'Dairy', 'Filipino Specialty', 'raw', 'pantry',
   100, 'g', 280, 18, 3, 22, 3, 0, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Macapuno', 'Macapuno (sweetened coconut strings)', array['macapuno'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 200, 0.5, 40, 5, 35, 2, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Ube halaya', 'Ube halaya (purple yam jam)', array['ube halaya', 'ube jam'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 230, 2, 45, 5, 30, 2, 40, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Pinipig', 'Pinipig (pounded young rice flakes)', array['pinipig'], 'Grain', 'Filipino Specialty', 'dried', 'pantry',
   100, 'g', 370, 7, 79, 1.5, 0, 2, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Puto', 'Puto (steamed rice cake)', array['puto'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 220, 4, 45, 2, 15, 1, 150, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 30, 'piece'),
  ('Bibingka', 'Bibingka (baked rice cake)', array['bibingka'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 250, 4.5, 45, 6, 20, 1, 200, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Kutsinta', 'Kutsinta (brown rice cake)', array['kutsinta'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 200, 2, 45, 0.5, 20, 0.5, 100, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 30, 'piece'),
  ('Suman', 'Suman (sticky rice cake)', array['suman'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 200, 3, 38, 4, 8, 1, 30, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Sapin-sapin', 'Sapin-sapin (layered rice cake)', array['sapin-sapin'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 230, 3, 45, 5, 25, 1, 40, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Palitaw', 'Palitaw (flattened rice cake)', array['palitaw'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 210, 3, 42, 4, 20, 1, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 30, 'piece'),
  ('Polvoron', 'Polvoron', array['polvoron'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 480, 6, 60, 24, 35, 1, 150, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', null, null),
  ('Pastillas', 'Pastillas (milk candy)', array['pastillas', 'pastillas de leche'], 'Dessert', 'Filipino Specialty', 'raw', 'pantry',
   100, 'g', 380, 8, 70, 8, 65, 0, 80, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Yema', 'Yema (custard candy)', array['yema'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 400, 6, 75, 9, 68, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Peanut brittle', 'Peanut brittle', array['peanut brittle'], 'Dessert', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 480, 10, 65, 22, 55, 3, 50, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Chicharon bulaklak', 'Chicharon bulaklak (fried pork intestine)', array['chicharon bulaklak', 'fried pork mesentery'], 'Street Food', 'Filipino Specialty', 'fried', 'main',
   100, 'g', 520, 35, 5, 40, 0, 0, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Betamax', 'Betamax (grilled blood cubes)', array['betamax', 'grilled blood cubes'], 'Street Food', 'Filipino Specialty', 'cooked', 'main',
   100, 'g', 150, 15, 2, 8, 0, 0, 300, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', 40, 'stick'),
  ('Isaw, grilled', 'Isaw (grilled intestine skewer)', array['isaw', 'grilled isaw'], 'Street Food', 'Filipino Specialty', 'cooked', 'main',
   100, 'g', 200, 16, 1, 14, 0, 0, 500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', 40, 'stick'),
  ('Taba ng talangka', 'Taba ng talangka (crab fat paste)', array['taba ng talangka', 'crab fat'], 'Condiment', 'Filipino Specialty', 'cooked', 'pantry',
   100, 'g', 350, 15, 5, 30, 1, 0, 800, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   600, 'kg', 'manual', null, null),
  ('Buro', 'Buro (fermented rice)', array['buro', 'fermented rice'], 'Fermented', 'Filipino Specialty', null, 'pantry',
   100, 'g', 110, 5, 20, 1, 0, 0, 600, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Palapa', 'Palapa (Mindanao aromatic spice paste)', array['palapa'], 'Condiment', 'Filipino Specialty', null, 'pantry',
   100, 'g', 90, 2, 15, 2.5, 0, 0, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Turon', 'Turon (fried banana lumpia)', array['turon'], 'Street Food', 'Filipino Specialty', 'fried', 'main',
   100, 'g', 250, 2, 40, 9, 20, 2, 100, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 60, 'piece'),
  ('Kwek-kwek', 'Kwek-kwek (fried battered quail eggs)', array['kwek-kwek', 'tokneneng'], 'Street Food', 'Filipino Specialty', 'fried', 'main',
   100, 'g', 280, 9, 25, 16, 1, 1, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Fish crackers', 'Fish crackers (kropek)', array['kropek', 'fish crackers'], 'Snack', 'Filipino Specialty', 'fried', 'pantry',
   100, 'g', 480, 8, 60, 22, 0, 0.5, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Ampalaya chips', 'Bitter gourd chips', array['ampalaya chips', 'bitter gourd chips'], 'Snack', 'Filipino Specialty', 'fried', 'pantry',
   100, 'g', 450, 5, 55, 22, 10, 5, 500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', null, null),
  ('Pili nuts', 'Pili nuts', array['pili nuts', 'pili'], 'Snack', 'Filipino Specialty', 'raw', 'pantry',
   100, 'g', 700, 11, 9, 71, 0, 5, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   800, 'kg', 'manual', null, null),
  ('Longganisa, native', 'Native longganisa (Vigan-style)', array['vigan longganisa', 'native longganisa', 'garlic longganisa'], 'Meat', 'Filipino Specialty', 'raw', 'main',
   100, 'g', 280, 16, 4, 22, 1, 0, 800, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', 30, 'link'),
  ('Malagkit flour', 'Glutinous rice flour', array['malagkit flour', 'glutinous rice flour', 'sweet rice flour'], 'Grain', 'Filipino Specialty', 'raw', 'pantry',
   100, 'g', 356, 6, 80, 1, 0, 2, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Bagnet', 'Bagnet (Ilocano crispy pork belly)', array['bagnet'], 'Meat', 'Filipino Specialty', 'fried', 'main',
   100, 'g', 550, 20, 2, 50, 0, 0, 600, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Adobo flakes', 'Adobo flakes (dried shredded adobo)', array['adobo flakes'], 'Meat', 'Filipino Specialty', 'dried', 'main',
   100, 'g', 350, 35, 5, 20, 2, 0, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null);
