-- Batch 4/~13: Beef (20 items). Same treatment as batches 1-3 — AI-estimated
-- placeholders, honestly tagged source='manual', verification_status='NEEDS_REVIEW',
-- so the "Ground from USDA" tool has real candidates to upgrade against, and any
-- item it can't confidently match still has usable (if approximate) data rather
-- than nulls blocking the meal-nutrition pipeline.
--
-- Covers raw cuts used in Filipino stews/braises (nilaga, bulalo, kare-kare,
-- mechado, caldereta), organs, and a few cured/canned staples (tapa, tocino,
-- corned beef) kept as their own canonical rows since curing/canning
-- genuinely changes the nutrition profile.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Beef chuck, raw', 'Beef chuck', array['beef chuck', 'kadera', 'chuck roast'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 215, 20, 0, 15, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   380, 'kg', 'manual', null, null),
  ('Beef brisket, raw', 'Beef brisket', array['beef brisket', 'brisket'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 270, 18, 0, 22, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   420, 'kg', 'manual', null, null),
  ('Beef short ribs, raw', 'Beef short ribs', array['beef short ribs', 'short ribs', 'tadyang ng baka'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 338, 17, 0, 30, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   450, 'kg', 'manual', null, null),
  ('Beef shank, raw', 'Beef shank', array['beef shank', 'shank', 'bulalo cut'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 152, 20, 0, 8, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Ground beef, raw', 'Ground beef', array['ground beef', 'giniling na baka'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 248, 17, 0, 20, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   380, 'kg', 'manual', null, null),
  ('Beef sirloin, raw', 'Beef sirloin', array['beef sirloin', 'sirloin'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 174, 21, 0, 10, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   480, 'kg', 'manual', null, null),
  ('Beef tenderloin, raw', 'Beef tenderloin', array['beef tenderloin', 'tenderloin'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 156, 21, 0, 8, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   650, 'kg', 'manual', null, null),
  ('Beef flank, raw', 'Beef flank', array['beef flank', 'flank steak'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 188, 20, 0, 12, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Beef round, raw', 'Beef round', array['beef round', 'round steak'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 138, 21, 0, 6, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   420, 'kg', 'manual', null, null),
  ('Beef liver, raw', 'Beef liver', array['beef liver', 'atay ng baka'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 130, 20.4, 3.9, 3.6, 0, 0, 69, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', null, null),
  ('Beef tripe, raw', 'Beef tripe', array['beef tripe', 'tuwalya', 'kare-kare tripe'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 123, 15, 0, 7, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Beef tongue, raw', 'Beef tongue', array['beef tongue', 'lengua', 'dila ng baka'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 217, 16, 0, 17, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   380, 'kg', 'manual', null, null),
  ('Beef oxtail, raw', 'Beef oxtail', array['beef oxtail', 'oxtail', 'buntot ng baka'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 215, 20, 0, 15, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Beef heart, raw', 'Beef heart', array['beef heart', 'puso ng baka'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 111, 17, 0.7, 4.5, 0, 0, 90, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Beef kidney, raw', 'Beef kidney', array['beef kidney', 'bato ng baka'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 98, 17, 0.8, 3, 0, 0, 180, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Beef bone marrow, raw', 'Beef bone marrow', array['beef bone marrow', 'utak ng buto', 'bulalo marrow'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 780, 6, 0, 84, 0, 0, 40, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', 150, 'bone'),
  ('Beef tapa', 'Beef tapa', array['beef tapa', 'tapa'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 226, 20, 5, 14, 3, 0, 750, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   420, 'kg', 'manual', null, null),
  ('Beef tocino', 'Beef tocino', array['beef tocino', 'tocino'], 'Beef', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 234, 15, 12, 14, 9, 0, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   380, 'kg', 'manual', null, null),
  ('Beef, cooked', 'Cooked beef', array['cooked beef', 'lutong karne ng baka'], 'Beef', 'Meat & Poultry', 'cooked', 'main',
   100, 'g', 239, 26, 0, 15, 0, 0, 70, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   450, 'kg', 'manual', null, null),
  ('Corned beef, canned', 'Corned beef', array['corned beef', 'canned corned beef'], 'Beef', 'Meat & Poultry', 'cooked', 'pantry',
   100, 'g', 205, 21, 1, 13, 0, 0, 800, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   420, 'kg', 'manual', 150, 'can');
