-- Batch 8/~13: Vegetables (40 items). Same treatment as batches 1-7 —
-- AI-estimated placeholders, honestly tagged source='manual',
-- verification_status='NEEDS_REVIEW', so the "Ground from USDA" tool has
-- real candidates to upgrade against, and any item it can't confidently
-- match still has usable (if approximate) data rather than nulls blocking
-- the meal-nutrition pipeline.
--
-- Scope: fruiting/pod vegetables and mushrooms only. Leafy greens and root
-- vegetables are deliberately excluded here — they're their own batch
-- next, per the category split in docs/ingredient-data-architecture.md.
-- A handful of common sauteed/boiled prep forms (grilled eggplant, cooked
-- squash, etc.) are kept as separate canonical rows from their raw form,
-- same cooking-state-as-identity rule as every prior batch.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Eggplant, raw', 'Eggplant', array['talong', 'eggplant', 'aubergine'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 25, 1, 5.9, 0.2, 3.5, 3, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', 150, 'piece'),
  ('Eggplant, grilled', 'Grilled eggplant', array['inihaw na talong', 'grilled eggplant'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 35, 1.2, 8.2, 0.3, 4.5, 4, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Okra, raw', 'Okra', array['okra'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 33, 1.9, 7.5, 0.2, 1.5, 3.2, 7, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', null, null),
  ('Okra, cooked', 'Cooked okra', array['cooked okra'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 35, 2, 7.6, 0.2, 1.5, 3.6, 8, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Bitter gourd, raw', 'Bitter gourd (ampalaya)', array['ampalaya', 'bitter gourd', 'bitter melon'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 17, 1, 3.7, 0.2, 2.5, 2.8, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Bitter gourd, cooked', 'Cooked bitter gourd (ampalaya)', array['cooked ampalaya', 'sauteed bitter gourd'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 22, 1.3, 4.7, 0.3, 2, 2.9, 8, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   110, 'kg', 'manual', null, null),
  ('Squash, raw', 'Squash (kalabasa)', array['kalabasa', 'squash', 'pumpkin'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 26, 1, 6, 0.1, 2.8, 0.5, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', 1500, 'piece'),
  ('Squash, cooked', 'Cooked squash (kalabasa)', array['cooked kalabasa', 'ginisang kalabasa'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 40, 1.4, 9, 0.2, 3.5, 2.5, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   65, 'kg', 'manual', null, null),
  ('Chayote, raw', 'Chayote (sayote)', array['sayote', 'chayote'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 19, 0.8, 4.5, 0.1, 1.7, 1.7, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   40, 'kg', 'manual', 250, 'piece'),
  ('Chayote, cooked', 'Cooked chayote (sayote)', array['cooked sayote', 'sauteed chayote'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 23, 0.9, 5.5, 0.2, 2, 2, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   55, 'kg', 'manual', null, null),
  ('Bottle gourd, raw', 'Bottle gourd (upo)', array['upo', 'bottle gourd'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 14, 0.6, 3.4, 0.02, 1.5, 1.2, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', 400, 'piece'),
  ('Bottle gourd, cooked', 'Cooked bottle gourd (upo)', array['cooked upo', 'sauteed upo'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 18, 0.8, 4.2, 0.1, 1.8, 1.5, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   65, 'kg', 'manual', null, null),
  ('Luffa, raw', 'Luffa (patola)', array['patola', 'luffa', 'sponge gourd'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 20, 1.2, 4.4, 0.2, 2, 1.5, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Luffa, cooked', 'Cooked luffa (patola)', array['cooked patola', 'sauteed luffa'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 24, 1.4, 5.2, 0.2, 2.2, 1.7, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   75, 'kg', 'manual', null, null),
  ('String beans, raw', 'String beans (sitaw)', array['sitaw', 'string beans', 'yardlong beans'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 47, 2.8, 8, 0.4, 3.3, 3.4, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('String beans, cooked', 'Cooked string beans (sitaw)', array['cooked sitaw', 'sauteed string beans'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 50, 3, 8.6, 0.4, 3, 3.6, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   110, 'kg', 'manual', null, null),
  ('Green beans, raw', 'Green beans (baguio beans)', array['baguio beans', 'green beans', 'french beans'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 31, 1.8, 7, 0.2, 3.3, 3.4, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Winged bean, raw', 'Winged bean (sigarilyas)', array['sigarilyas', 'winged bean'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 49, 2.9, 10, 0.3, 1, 2.6, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Tomato, raw', 'Tomato', array['kamatis', 'tomato'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 18, 0.9, 3.9, 0.2, 2.6, 1.2, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', 90, 'piece'),
  ('Bell pepper, green, raw', 'Green bell pepper', array['green bell pepper', 'siling bell'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 20, 0.9, 4.6, 0.2, 2.4, 1.7, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 120, 'piece'),
  ('Bell pepper, red, raw', 'Red bell pepper', array['red bell pepper'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 31, 1, 6, 0.3, 4.2, 2.1, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', 120, 'piece'),
  ('Cucumber, raw', 'Cucumber', array['pipino', 'cucumber'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 15, 0.65, 3.6, 0.1, 1.7, 0.5, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', 200, 'piece'),
  ('Zucchini, raw', 'Zucchini', array['zucchini', 'baby squash'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 17, 1.2, 3.1, 0.3, 2.5, 1, 8, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Cauliflower, raw', 'Cauliflower', array['cauliflower'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 25, 1.9, 5, 0.3, 1.9, 2, 30, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Broccoli, raw', 'Broccoli', array['broccoli'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 34, 2.8, 6.6, 0.4, 1.7, 2.6, 33, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Green peas, raw', 'Green peas', array['green peas', 'garden peas'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 81, 5.4, 14.5, 0.4, 5.7, 5.7, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Snow peas, raw', 'Snow peas', array['snow peas', 'snap peas'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 42, 2.8, 7.6, 0.2, 4, 2.6, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', null, null),
  ('Chili pepper, green, raw', 'Green chili pepper (siling pang-sigang)', array['siling pang-sigang', 'green chili', 'green finger chili'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 40, 1.9, 9, 0.4, 5.1, 1.5, 7, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Chili pepper, red, raw', 'Red chili pepper (siling labuyo)', array['siling labuyo', 'bird''s eye chili', 'red chili'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 40, 1.87, 8.8, 0.4, 5.3, 1.5, 9, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Banana blossom, raw', 'Banana blossom (puso ng saging)', array['puso ng saging', 'banana blossom', 'banana heart'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 51, 1.6, 12.6, 0.6, 2, 5.7, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', 300, 'piece'),
  ('Jackfruit, unripe, raw', 'Unripe jackfruit (langka)', array['langka', 'unripe jackfruit', 'green jackfruit'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 68, 3.2, 12.6, 0.6, 0.5, 4.5, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', null, null),
  ('Button mushroom, raw', 'Button mushroom', array['button mushroom', 'white mushroom'], 'Mushroom', 'Vegetables', 'raw', 'main',
   100, 'g', 25, 3.1, 3.3, 0.3, 2, 1, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Button mushroom, cooked', 'Cooked button mushroom', array['cooked button mushroom', 'sauteed mushroom'], 'Mushroom', 'Vegetables', 'cooked', 'main',
   100, 'g', 33, 3.6, 4.3, 0.5, 2, 1.3, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   280, 'kg', 'manual', null, null),
  ('Oyster mushroom, raw', 'Oyster mushroom', array['oyster mushroom', 'abalone mushroom'], 'Mushroom', 'Vegetables', 'raw', 'main',
   100, 'g', 33, 3.3, 6.1, 0.4, 1.1, 2.3, 18, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', null, null),
  ('Oyster mushroom, cooked', 'Cooked oyster mushroom', array['cooked oyster mushroom', 'sauteed oyster mushroom'], 'Mushroom', 'Vegetables', 'cooked', 'main',
   100, 'g', 38, 3.6, 7, 0.5, 1.2, 2.5, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Green papaya, raw', 'Green papaya', array['green papaya', 'unripe papaya'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 27, 0.5, 6.7, 0.1, 2.8, 1.7, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   40, 'kg', 'manual', null, null),
  ('Green papaya, cooked', 'Cooked green papaya', array['cooked green papaya', 'tinolang papaya'], 'Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 30, 0.6, 7.3, 0.1, 3, 1.9, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   55, 'kg', 'manual', null, null),
  ('Asparagus, raw', 'Asparagus', array['asparagus'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 20, 2.2, 3.9, 0.1, 1.9, 2.1, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Celery, raw', 'Celery', array['celery'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 14, 0.7, 3, 0.2, 1.3, 1.6, 80, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Squash blossom, raw', 'Squash blossom', array['squash blossom', 'kalabasa flower', 'pumpkin flower'], 'Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 15, 1.9, 2.5, 0.2, 1.3, 1.5, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null);
