-- Batch 5/~13: Fish & seafood (40 items). Same treatment as batches 1-4 —
-- AI-estimated placeholders, honestly tagged source='manual',
-- verification_status='NEEDS_REVIEW', so the "Ground from USDA" tool has
-- real candidates to upgrade against, and any item it can't confidently
-- match still has usable (if approximate) data rather than nulls blocking
-- the meal-nutrition pipeline.
--
-- Covers everyday Filipino finfish (bangus, tilapia, galunggong, tuna,
-- sardines) in raw/fried/dried/canned variants (kept as separate canonical
-- rows since frying/drying/canning genuinely changes the nutrition
-- profile, same cooking-state-as-identity rule as poultry/pork/beef),
-- shellfish, mollusks/cephalopods, and two processed staples (fish balls,
-- tinapa). Patis/bagoong (fish sauce/paste) deliberately excluded — those
-- belong in the later condiments/sauces batch, not here.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Milkfish, raw', 'Milkfish (bangus)', array['bangus', 'milkfish'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 140, 20, 0, 6.7, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', null, null),
  ('Milkfish, fried', 'Fried bangus', array['fried bangus', 'pritong bangus'], 'Fish', 'Fish & Seafood', 'fried', 'main',
   100, 'g', 200, 22, 1, 12, 0, 0, 300, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   280, 'kg', 'manual', null, null),
  ('Milkfish, dried', 'Dried bangus (daing)', array['daing na bangus', 'dried bangus'], 'Fish', 'Fish & Seafood', 'dried', 'main',
   100, 'g', 250, 40, 0, 10, 0, 0, 1800, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Tilapia, raw', 'Tilapia', array['tilapia'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 96, 20, 0, 1.7, 0, 0, 52, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   140, 'kg', 'manual', null, null),
  ('Tilapia, fried', 'Fried tilapia', array['fried tilapia', 'pritong tilapia'], 'Fish', 'Fish & Seafood', 'fried', 'main',
   100, 'g', 182, 22, 1, 10, 0, 0, 280, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Round scad, raw', 'Round scad (galunggong)', array['galunggong', 'round scad'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 107, 20, 0, 3, 0, 0, 70, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Round scad, fried', 'Fried galunggong', array['fried galunggong', 'pritong galunggong'], 'Fish', 'Fish & Seafood', 'fried', 'main',
   100, 'g', 200, 22, 1, 12, 0, 0, 320, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   240, 'kg', 'manual', null, null),
  ('Tuna, raw', 'Tuna', array['tuna', 'yellowfin tuna', 'tambakol'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 105, 24, 0, 1, 0, 0, 45, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   320, 'kg', 'manual', null, null),
  ('Tuna, canned in oil', 'Canned tuna (in oil)', array['canned tuna', 'tuna in oil'], 'Fish', 'Fish & Seafood', 'cooked', 'pantry',
   100, 'g', 190, 25, 0, 10, 0, 0, 350, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', 155, 'can'),
  ('Tuna, canned in water', 'Canned tuna (in water)', array['canned tuna in water', 'tuna flakes'], 'Fish', 'Fish & Seafood', 'cooked', 'pantry',
   100, 'g', 113, 26, 0, 1, 0, 0, 300, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   360, 'kg', 'manual', 155, 'can'),
  ('Mackerel, raw', 'Mackerel (alumahan)', array['alumahan', 'hasa-hasa', 'mackerel'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 184, 19, 0, 12, 0, 0, 70, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Mackerel, fried', 'Fried mackerel', array['fried alumahan', 'pritong alumahan'], 'Fish', 'Fish & Seafood', 'fried', 'main',
   100, 'g', 250, 21, 1, 18, 0, 0, 320, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   260, 'kg', 'manual', null, null),
  ('Catfish, raw', 'Catfish (hito)', array['hito', 'catfish'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 108, 18, 0, 4, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   160, 'kg', 'manual', null, null),
  ('Grouper, raw', 'Grouper (lapu-lapu)', array['lapu-lapu', 'grouper'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 94, 20, 0, 1.5, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   380, 'kg', 'manual', null, null),
  ('Sardines, fresh, raw', 'Fresh sardines (tamban)', array['tamban', 'fresh sardines'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 161, 20, 0, 9, 0, 0, 70, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Sardines, canned in tomato sauce', 'Canned sardines', array['canned sardines', 'sardinas'], 'Fish', 'Fish & Seafood', 'cooked', 'pantry',
   100, 'g', 179, 18, 2, 11, 1, 0, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 155, 'can'),
  ('Anchovy, fresh, raw', 'Fresh anchovy (dilis)', array['dilis', 'fresh anchovy'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 117, 18, 0, 5, 0, 0, 100, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Anchovy, dried', 'Dried anchovy (dilis)', array['dried dilis', 'dried anchovy'], 'Fish', 'Fish & Seafood', 'dried', 'main',
   100, 'g', 252, 45, 0, 8, 0, 0, 2500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Herring, dried', 'Dried herring (tuyo)', array['tuyo', 'dried herring'], 'Fish', 'Fish & Seafood', 'dried', 'main',
   100, 'g', 276, 42, 0, 12, 0, 0, 2200, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Rabbitfish, dried', 'Dried rabbitfish (danggit)', array['danggit', 'dried rabbitfish'], 'Fish', 'Fish & Seafood', 'dried', 'main',
   100, 'g', 230, 44, 0, 6, 0, 0, 2000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   450, 'kg', 'manual', null, null),
  ('Mudfish, raw', 'Mudfish (dalag)', array['dalag', 'mudfish', 'snakehead'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 85, 19, 0, 1, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Mullet, raw', 'Mullet (banak)', array['banak', 'mullet'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 112, 19, 0, 4, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Blue marlin, raw', 'Blue marlin', array['blue marlin', 'marlin'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 115, 22, 0, 3, 0, 0, 50, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Cream dory, raw', 'Cream dory fillet', array['cream dory', 'dory fillet', 'pangasius'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 96, 15, 0, 4, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', null, null),
  ('Salmon, raw', 'Salmon', array['salmon'], 'Fish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 197, 20, 0, 13, 0, 0, 50, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   650, 'kg', 'manual', null, null),
  ('Squid, raw', 'Squid (pusit)', array['pusit', 'squid'], 'Mollusk', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 89, 16, 3, 1.4, 0, 0, 44, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   280, 'kg', 'manual', null, null),
  ('Squid, dried', 'Dried squid', array['dried pusit', 'dried squid'], 'Mollusk', 'Fish & Seafood', 'dried', 'main',
   100, 'g', 288, 58, 5, 4, 0, 0, 700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null),
  ('Octopus, raw', 'Octopus (pugita)', array['pugita', 'octopus'], 'Mollusk', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 85, 15, 4, 1, 0, 0, 230, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Shrimp, raw', 'Shrimp (hipon)', array['hipon', 'shrimp', 'prawn'], 'Shellfish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 93, 20, 0.9, 1, 0, 0, 120, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   380, 'kg', 'manual', null, null),
  ('Shrimp, dried', 'Dried shrimp (hibi)', array['hibi', 'dried shrimp'], 'Shellfish', 'Fish & Seafood', 'dried', 'main',
   100, 'g', 275, 60, 2, 3, 0, 0, 3000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   600, 'kg', 'manual', null, null),
  ('Blue crab, raw', 'Blue crab (alimasag)', array['alimasag', 'blue crab'], 'Shellfish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 81, 18, 0, 1, 0, 0, 300, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Crab meat, cooked', 'Cooked crab meat', array['crab meat', 'cooked crab meat'], 'Shellfish', 'Fish & Seafood', 'cooked', 'main',
   100, 'g', 94, 20, 0, 1.5, 0, 0, 350, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null),
  ('Mud crab, raw', 'Mud crab (alimango)', array['alimango', 'mud crab'], 'Shellfish', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 88, 18, 0.5, 1.5, 0, 0, 320, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   450, 'kg', 'manual', null, null),
  ('Mussels, raw', 'Mussels (tahong)', array['tahong', 'mussels'], 'Mollusk', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 84, 12, 4, 2.2, 0, 0, 280, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Oysters, raw', 'Oysters (talaba)', array['talaba', 'oysters'], 'Mollusk', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 77, 9, 4.7, 2.5, 0, 0, 90, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Clams, raw', 'Clams (halaan)', array['halaan', 'clams'], 'Mollusk', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 74, 12.8, 2.6, 1, 0, 0, 56, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Scallops, raw', 'Scallops', array['scallops'], 'Mollusk', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 87, 17, 3, 0.8, 0, 0, 160, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   700, 'kg', 'manual', null, null),
  ('Smoked fish, whole', 'Smoked fish (tinapa)', array['tinapa', 'smoked fish'], 'Fish', 'Fish & Seafood', 'cooked', 'main',
   100, 'g', 184, 28, 0, 8, 0, 0, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', 80, 'piece'),
  ('Fish balls, raw', 'Fish balls', array['fish balls', 'bola-bola'], 'Processed Seafood', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 137, 8, 15, 5, 1, 0, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 15, 'piece'),
  ('Crab sticks, raw', 'Crab sticks (imitation crab)', array['crab sticks', 'imitation crab', 'kani'], 'Processed Seafood', 'Fish & Seafood', 'raw', 'main',
   100, 'g', 101, 9, 15, 0.5, 3, 0, 500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', 15, 'stick');
