-- Batch 9/~13: Leafy greens & root vegetables (35 items). Same treatment
-- as batches 1-8 — AI-estimated placeholders, honestly tagged
-- source='manual', verification_status='NEEDS_REVIEW', so the "Ground
-- from USDA" tool has real candidates to upgrade against, and any item it
-- can't confidently match still has usable (if approximate) data rather
-- than nulls blocking the meal-nutrition pipeline.
--
-- Shares food_group='Vegetables' with batch 8 (fruiting/pod vegetables +
-- mushrooms) so the app can browse/filter all vegetables together;
-- category ('Leafy Green' / 'Root Vegetable') distinguishes the subtype.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Water spinach, raw', 'Water spinach (kangkong)', array['kangkong', 'water spinach'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 19, 2.6, 3.1, 0.2, 0.4, 2.1, 113, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   40, 'kg', 'manual', null, null),
  ('Water spinach, cooked', 'Cooked water spinach (kangkong)', array['cooked kangkong', 'ginisang kangkong'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 22, 2.9, 3.5, 0.3, 0.5, 2.3, 130, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   55, 'kg', 'manual', null, null),
  ('Moringa leaves, raw', 'Moringa leaves (malunggay)', array['malunggay', 'moringa leaves'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 64, 6.8, 8.3, 1.4, 0, 2, 9, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Moringa leaves, cooked', 'Cooked moringa leaves (malunggay)', array['cooked malunggay', 'tinolang malunggay'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 70, 7.5, 9, 1.5, 0, 2.2, 15, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   75, 'kg', 'manual', null, null),
  ('Bok choy, raw', 'Bok choy (pechay)', array['pechay', 'bok choy', 'pak choi'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 13, 1.5, 2.2, 0.2, 1.2, 1, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Bok choy, cooked', 'Cooked bok choy (pechay)', array['cooked pechay', 'ginisang pechay'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 15, 1.6, 2.5, 0.2, 1.3, 1.2, 80, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   75, 'kg', 'manual', null, null),
  ('Napa cabbage, raw', 'Napa cabbage (wombok)', array['napa cabbage', 'wombok', 'pechay baguio'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 16, 1.2, 3.2, 0.2, 1.2, 1.2, 9, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', 1000, 'head'),
  ('Cabbage, raw', 'Cabbage', array['repolyo', 'cabbage'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 25, 1.3, 5.8, 0.1, 3.2, 2.5, 18, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', 1200, 'head'),
  ('Cabbage, cooked', 'Cooked cabbage', array['cooked cabbage', 'ginisang repolyo'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 23, 1.1, 5.3, 0.1, 2.8, 2.2, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   75, 'kg', 'manual', null, null),
  ('Mustard greens, raw', 'Mustard greens (mustasa)', array['mustasa', 'mustard greens'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 27, 2.9, 4.7, 0.4, 1.3, 3.2, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Mustard greens, cooked', 'Cooked mustard greens (mustasa)', array['cooked mustasa'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 30, 3.2, 5.1, 0.4, 1.4, 3.4, 25, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   75, 'kg', 'manual', null, null),
  ('Spinach, raw', 'Spinach', array['spinach'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 23, 2.9, 3.6, 0.4, 0.4, 2.2, 79, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Spinach, cooked', 'Cooked spinach', array['cooked spinach', 'sauteed spinach'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 23, 3, 3.8, 0.3, 0.4, 2.4, 70, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   110, 'kg', 'manual', null, null),
  ('Jute leaves, raw', 'Jute leaves (saluyot)', array['saluyot', 'jute leaves'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 38, 4.5, 5.5, 0.5, 0, 2, 27, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', null, null),
  ('Jute leaves, cooked', 'Cooked jute leaves (saluyot)', array['cooked saluyot', 'tinolang saluyot'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 41, 4.8, 6, 0.5, 0, 2.2, 32, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   65, 'kg', 'manual', null, null),
  ('Sweet potato tops, raw', 'Sweet potato leaves (camote tops)', array['camote tops', 'talbos ng kamote', 'sweet potato leaves'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 35, 2.6, 6.1, 0.5, 0, 2.4, 76, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   40, 'kg', 'manual', null, null),
  ('Sweet potato tops, cooked', 'Cooked sweet potato leaves (camote tops)', array['cooked camote tops', 'ginisang talbos ng kamote'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 38, 2.8, 6.8, 0.5, 0, 2.6, 90, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   55, 'kg', 'manual', null, null),
  ('Lettuce, raw', 'Lettuce', array['lettuce'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 15, 1.4, 2.9, 0.2, 0.8, 1.3, 28, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', 250, 'head'),
  ('Malabar spinach, raw', 'Malabar spinach (alugbati)', array['alugbati', 'malabar spinach'], 'Leafy Green', 'Vegetables', 'raw', 'main',
   100, 'g', 19, 1.8, 3.4, 0.3, 0, 1.7, 24, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', null, null),
  ('Malabar spinach, cooked', 'Cooked Malabar spinach (alugbati)', array['cooked alugbati'], 'Leafy Green', 'Vegetables', 'cooked', 'main',
   100, 'g', 22, 2, 3.8, 0.3, 0, 1.9, 30, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   65, 'kg', 'manual', null, null),
  ('Potato, raw', 'Potato', array['patatas', 'potato'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 77, 2, 17.5, 0.1, 0.8, 2.1, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', 120, 'piece'),
  ('Potato, cooked', 'Cooked potato', array['cooked potato', 'boiled potato'], 'Root Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 87, 1.9, 20.1, 0.1, 0.9, 1.8, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   110, 'kg', 'manual', null, null),
  ('Sweet potato, raw', 'Sweet potato (kamote)', array['kamote', 'sweet potato'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 86, 1.6, 20.1, 0.1, 4.2, 3, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', 150, 'piece'),
  ('Sweet potato, cooked', 'Cooked sweet potato (kamote)', array['cooked kamote', 'boiled kamote'], 'Root Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 90, 2, 20.7, 0.1, 4.5, 3.3, 36, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   75, 'kg', 'manual', null, null),
  ('Taro, raw', 'Taro (gabi)', array['gabi', 'taro'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 112, 1.5, 26.5, 0.2, 0.5, 4.1, 11, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Taro, cooked', 'Cooked taro (gabi)', array['cooked gabi', 'boiled taro'], 'Root Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 98, 1.8, 22, 0.2, 0.5, 3.7, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   110, 'kg', 'manual', null, null),
  ('Cassava, raw', 'Cassava (kamoteng kahoy)', array['kamoteng kahoy', 'cassava', 'yuca'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 160, 1.4, 38, 0.3, 1.7, 1.8, 14, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', null, null),
  ('Cassava, cooked', 'Cooked cassava (kamoteng kahoy)', array['cooked kamoteng kahoy', 'boiled cassava'], 'Root Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 112, 0.6, 27.1, 0.3, 1.2, 1.5, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   65, 'kg', 'manual', null, null),
  ('Carrot, raw', 'Carrot', array['karot', 'carrot'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 41, 0.9, 9.6, 0.2, 4.7, 2.8, 69, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', 70, 'piece'),
  ('Carrot, cooked', 'Cooked carrot', array['cooked carrot', 'boiled carrot'], 'Root Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 35, 0.8, 8.2, 0.2, 4, 3, 58, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   110, 'kg', 'manual', null, null),
  ('Radish, raw', 'Radish (labanos)', array['labanos', 'radish', 'daikon'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 16, 0.7, 3.4, 0.1, 1.9, 1.6, 21, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', 200, 'piece'),
  ('Purple yam, raw', 'Purple yam (ube)', array['ube', 'purple yam'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 118, 1.5, 27.9, 0.2, 0.5, 4.1, 9, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Purple yam, cooked', 'Cooked purple yam (ube)', array['cooked ube', 'boiled ube'], 'Root Vegetable', 'Vegetables', 'cooked', 'main',
   100, 'g', 120, 1.5, 28, 0.2, 0.5, 3.9, 12, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Jicama, raw', 'Jicama (singkamas)', array['singkamas', 'jicama'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 38, 0.7, 10.5, 0.1, 1.8, 4.9, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Beet, raw', 'Beet', array['beet', 'beetroot'], 'Root Vegetable', 'Vegetables', 'raw', 'main',
   100, 'g', 43, 1.6, 9.6, 0.2, 6.8, 2.8, 78, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 100, 'piece');
