-- Batch 13/~13: Condiments, sauces & vinegars (50 items). Same treatment
-- as batches 1-12 — AI-estimated placeholders, honestly tagged
-- source='manual', verification_status='NEEDS_REVIEW', so the "Ground
-- from USDA" tool has real candidates to upgrade against, and any item it
-- can't confidently match still has usable (if approximate) data rather
-- than nulls blocking the meal-nutrition pipeline.
--
-- state=null throughout, matching the established convention from the
-- original batch-1 seed (Soy sauce, Vinegar white, Bay leaf, Black
-- pepper, Cooking oil, Salt) — raw/cooked/fried/dried doesn't apply to a
-- bottled/jarred condiment. Reuses category='Condiments & Sauces' and
-- food_group='Condiments' from that same seed rather than introducing a
-- new bucket. Liquids (vinegars, soy sauce, fish sauce, most sauces) use
-- basis_unit='ml'; pastes/solids (shrimp paste, mustard, mayo, broth
-- cubes) use basis_unit='g'.
--
-- Deliberately excludes plain 'Soy sauce' and 'Vinegar, white', already
-- seeded in batch 1 — only genuinely new variants added here.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Vinegar, cane', 'Cane vinegar', array['sukang puti', 'cane vinegar'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 18, 0, 0.9, 0, 0.4, 0, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   40, 'L', 'manual', null, null),
  ('Vinegar, coconut', 'Coconut vinegar', array['sukang tuba', 'coconut vinegar'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 20, 0, 1, 0, 0.5, 0, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'L', 'manual', null, null),
  ('Vinegar, apple cider', 'Apple cider vinegar', array['apple cider vinegar', 'acv'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 22, 0, 0.9, 0, 0.4, 0, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'L', 'manual', null, null),
  ('Vinegar, balsamic', 'Balsamic vinegar', array['balsamic vinegar'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 88, 0.5, 17, 0, 15, 0, 23, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'L', 'manual', null, null),
  ('Vinegar, rice', 'Rice vinegar', array['rice vinegar'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 18, 0, 1.5, 0, 0.3, 0, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Vinegar, spiced', 'Spiced vinegar (sawsawan)', array['sawsawan', 'spiced vinegar', 'sukang may sili'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 20, 0.1, 1.5, 0, 0.3, 0, 200, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'L', 'manual', null, null),
  ('Soy sauce, dark', 'Dark soy sauce', array['dark soy sauce', 'sweet soy sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 130, 6, 20, 0.1, 15, 0.5, 3000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'L', 'manual', null, null),
  ('Soy sauce, low sodium', 'Low sodium soy sauce', array['low sodium soy sauce', 'light soy sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 53, 8, 4.9, 0.1, 0.4, 0.8, 2900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'L', 'manual', null, null),
  ('Fish sauce', 'Fish sauce (patis)', array['patis', 'fish sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 35, 5, 3.6, 0, 0, 0, 7850, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'L', 'manual', null, null),
  ('Shrimp paste, raw', 'Shrimp paste (bagoong alamang)', array['bagoong alamang', 'shrimp paste'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 85, 10, 4, 2.5, 0, 0, 4500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Shrimp paste, sauteed', 'Sauteed shrimp paste (bagoong guisado)', array['bagoong guisado', 'sauteed bagoong'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 160, 8, 18, 6, 12, 0, 2000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Fermented fish paste', 'Fermented fish paste (bagoong isda)', array['bagoong isda', 'fermented fish paste'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 70, 9, 2, 2, 0, 0, 5000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Atchara', 'Atchara (pickled papaya relish)', array['atchara', 'pickled papaya'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 60, 0.5, 14, 0.1, 12, 1, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Ketchup, tomato', 'Tomato ketchup', array['ketchup', 'tomato ketchup'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 112, 1.2, 27, 0.2, 22, 0.5, 950, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'L', 'manual', null, null),
  ('Ketchup, banana', 'Banana ketchup', array['banana ketchup'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 150, 0.3, 37, 0.1, 30, 0.5, 700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'L', 'manual', null, null),
  ('Tomato sauce', 'Tomato sauce', array['tomato sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 29, 1.6, 6.6, 0.3, 3.9, 1.6, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'L', 'manual', null, null),
  ('Tomato paste', 'Tomato paste', array['tomato paste'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 82, 4.3, 18.9, 0.5, 12, 4.1, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Oyster sauce', 'Oyster sauce', array['oyster sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 51, 1.4, 10.9, 0.3, 8, 0.3, 2700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Hoisin sauce', 'Hoisin sauce', array['hoisin sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 220, 2.5, 44, 3.4, 22, 2, 1700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'L', 'manual', null, null),
  ('Worcestershire sauce', 'Worcestershire sauce', array['worcestershire sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 78, 0, 19.5, 0, 15, 0, 980, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'L', 'manual', null, null),
  ('Mayonnaise', 'Mayonnaise', array['mayonnaise', 'mayo'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 680, 1, 0.6, 75, 0.6, 0, 635, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Mustard, prepared', 'Prepared mustard', array['mustard', 'yellow mustard', 'prepared mustard'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 66, 4.4, 5.4, 3.3, 2.2, 3.3, 1100, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Mustard, dijon', 'Dijon mustard', array['dijon mustard'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 150, 7, 6, 11, 1, 3, 1750, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Barbecue sauce', 'Barbecue sauce', array['bbq sauce', 'barbecue sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 172, 1, 40, 0.6, 33, 1, 800, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'L', 'manual', null, null),
  ('Sweet chili sauce', 'Sweet chili sauce', array['sweet chili sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 180, 0.5, 44, 0.2, 40, 0.5, 600, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Sriracha', 'Sriracha', array['sriracha', 'sriracha sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 93, 1.9, 19, 0.9, 14, 1, 2000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'L', 'manual', null, null),
  ('Liver sauce', 'Liver sauce (Mang Tomas style)', array['liver sauce', 'lechon sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 130, 3, 20, 4, 8, 1, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'L', 'manual', null, null),
  ('Gravy, brown', 'Brown gravy', array['brown gravy', 'gravy'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 40, 1.5, 5, 1.5, 1, 0.3, 350, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Gravy, chicken', 'Chicken gravy', array['chicken gravy'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 45, 2, 4.5, 2, 0.5, 0.2, 380, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'L', 'manual', null, null),
  ('Peanut sauce', 'Peanut sauce (kare-kare base)', array['peanut sauce', 'kare-kare sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 320, 12, 15, 25, 6, 4, 600, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'L', 'manual', null, null),
  ('Coconut milk, canned', 'Coconut milk', array['gata', 'coconut milk', 'canned coconut milk'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 230, 2.3, 5.5, 24, 3.3, 2.2, 15, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'L', 'manual', null, null),
  ('Coconut cream, canned', 'Coconut cream', array['kakang gata', 'coconut cream', 'canned coconut cream'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 330, 3.6, 6.7, 34.7, 3.3, 2.2, 15, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'L', 'manual', null, null),
  ('Chili garlic sauce', 'Chili garlic sauce', array['chili garlic sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 50, 1.5, 10, 0.5, 6, 1.5, 1500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'L', 'manual', null, null),
  ('Chili oil', 'Chili oil', array['chili oil'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 880, 0, 2, 96, 0, 1, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'L', 'manual', null, null),
  ('Salted black beans', 'Salted black beans (tausi)', array['tausi', 'salted black beans', 'fermented black beans'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 180, 14, 20, 4, 2, 8, 3000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Miso paste', 'Miso paste', array['miso', 'miso paste'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 199, 11.7, 26, 6, 6.2, 5.4, 3728, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Honey', 'Honey', array['pulot', 'honey'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 304, 0.3, 82.4, 0, 82.1, 0.2, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null),
  ('Relish, sweet pickle', 'Sweet pickle relish', array['relish', 'sweet pickle relish'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 130, 0.4, 32, 0.3, 26, 1.2, 700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Salted egg sauce', 'Salted egg sauce', array['salted egg sauce', 'salted egg cream sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 350, 6, 10, 32, 4, 0.5, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'L', 'manual', null, null),
  ('Cheese sauce', 'Cheese sauce', array['cheese sauce', 'cheese dip'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 200, 8, 8, 15, 3, 0.2, 700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'L', 'manual', null, null),
  ('Toyomansi', 'Toyomansi (soy-calamansi dip)', array['toyomansi', 'soy calamansi'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 55, 6, 6, 0.1, 2, 0.3, 4000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'L', 'manual', null, null),
  ('Ranch dressing', 'Ranch dressing', array['ranch dressing', 'ranch'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 430, 1, 5, 45, 3, 0.2, 700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'L', 'manual', null, null),
  ('Thousand island dressing', 'Thousand island dressing', array['thousand island dressing', 'thousand island'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 380, 0.6, 16, 35, 13, 0.5, 700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   280, 'L', 'manual', null, null),
  ('Calamansi juice, bottled', 'Bottled calamansi juice', array['calamansi juice', 'bottled calamansi'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 40, 0.3, 10, 0.1, 8, 0.2, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'L', 'manual', null, null),
  ('Adobo sauce, bottled', 'Bottled adobo sauce', array['adobo sauce', 'adobo seasoning sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 90, 3, 12, 2.5, 5, 0.5, 2500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Sinigang mix, powdered', 'Sinigang mix (tamarind soup base)', array['sinigang mix', 'sinigang sa sampalok mix'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 300, 2, 70, 1, 40, 2, 8000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Beef broth cubes', 'Beef broth cubes (bouillon)', array['beef cubes', 'beef bouillon', 'beef broth cubes'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 250, 10, 20, 15, 3, 1, 20000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', 10, 'cube'),
  ('Chicken broth cubes', 'Chicken broth cubes (bouillon)', array['chicken cubes', 'chicken bouillon', 'chicken broth cubes'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'g', 260, 9, 22, 16, 3, 1, 19000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   280, 'kg', 'manual', 10, 'cube'),
  ('Sweet and sour sauce', 'Sweet and sour sauce', array['sweet and sour sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 130, 0.3, 32, 0.1, 28, 0.3, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Teriyaki sauce', 'Teriyaki sauce', array['teriyaki sauce'], 'Condiments & Sauces', 'Condiments', null, 'pantry',
   100, 'ml', 89, 5.9, 16, 0, 11, 0.2, 3400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'L', 'manual', null, null);
