-- Batch 2/~13: Poultry (20 items). Same treatment as the original 10 test
-- ingredients (supabase/seed.sql) — AI-estimated placeholders, honestly
-- tagged source='manual', verification_status='NEEDS_REVIEW', so the
-- "Ground from USDA" tool has real candidates to upgrade against, and any
-- item it can't confidently match still has usable (if approximate) data
-- rather than nulls blocking the meal-nutrition pipeline.
--
-- Excludes "Chicken breast, raw" — already seeded in the original 10.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Chicken thigh, raw', 'Chicken thigh', array['chicken thigh', 'hita ng manok', 'thigh'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 209, 18.6, 0, 14.7, 0, 0, 79, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', 120, 'thigh'),
  ('Chicken drumstick, raw', 'Chicken drumstick', array['chicken drumstick', 'paa ng manok', 'drumstick'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 172, 18.3, 0, 10.6, 0, 0, 77, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   170, 'kg', 'manual', 90, 'drumstick'),
  ('Chicken wing, raw', 'Chicken wing', array['chicken wing', 'pakpak ng manok', 'wing'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 203, 18.4, 0, 13.9, 0, 0, 74, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   190, 'kg', 'manual', 45, 'wing'),
  ('Chicken leg quarter, raw', 'Chicken leg quarter', array['chicken leg quarter', 'leg quarter'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 180, 17, 0, 12, 0, 0, 80, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 250, 'leg quarter'),
  ('Whole chicken, raw', 'Whole chicken', array['whole chicken', 'buong manok', 'manok'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 215, 18.6, 0, 15.1, 0, 0, 70, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   160, 'kg', 'manual', 1200, 'whole chicken'),
  ('Chicken liver, raw', 'Chicken liver', array['chicken liver', 'atay ng manok', 'atay'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 119, 16.9, 0.7, 4.8, 0, 0, 71, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   140, 'kg', 'manual', 35, 'liver'),
  ('Chicken gizzard, raw', 'Chicken gizzard', array['chicken gizzard', 'balunbalunan'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 94, 17.7, 0, 2.1, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', 25, 'gizzard'),
  ('Chicken heart, raw', 'Chicken heart', array['chicken heart', 'puso ng manok'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 153, 15.6, 0.1, 9.3, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   130, 'kg', 'manual', 8, 'heart'),
  ('Chicken feet, raw', 'Chicken feet', array['chicken feet', 'paa', 'adidas'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 215, 19.4, 0.1, 14.6, 0, 0, 61, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', 35, 'foot'),
  ('Ground chicken, raw', 'Ground chicken', array['ground chicken', 'giniling na manok'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 143, 17.4, 0, 8.1, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Chicken skin, raw', 'Chicken skin', array['chicken skin', 'balat ng manok'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 458, 12.2, 0, 45.2, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Chicken neck, raw', 'Chicken neck', array['chicken neck', 'leeg ng manok'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 172, 15, 0, 12, 0, 0, 70, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', 30, 'neck'),
  ('Chicken back, raw', 'Chicken back', array['chicken back', 'likod ng manok'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 216, 14, 0, 17, 0, 0, 70, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', null, null),
  ('Chicken breast, bone-in, raw', 'Chicken breast (bone-in)', array['chicken breast bone-in', 'dibdib ng manok'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 172, 20.9, 0, 9.3, 0, 0, 68, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', 200, 'bone-in breast'),
  ('Chicken breast, cooked', 'Cooked chicken breast', array['cooked chicken breast', 'lutong dibdib ng manok'], 'Poultry', 'Meat & Poultry', 'cooked', 'main',
   100, 'g', 165, 31, 0, 3.6, 0, 0, 74, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', null, null),
  ('Chicken thigh, cooked', 'Cooked chicken thigh', array['cooked chicken thigh', 'lutong hita'], 'Poultry', 'Meat & Poultry', 'cooked', 'main',
   100, 'g', 209, 26, 0, 10.9, 0, 0, 84, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Chicken, fried', 'Fried chicken', array['fried chicken', 'pritong manok'], 'Poultry', 'Meat & Poultry', 'fried', 'main',
   100, 'g', 246, 20.1, 8.3, 14.8, 0.2, 0.3, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Native chicken, raw', 'Native chicken', array['native chicken', 'manok na bisaya', 'manok na pinoy'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 172, 20, 0, 9, 0, 0, 75, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   280, 'kg', 'manual', null, null),
  ('Duck, whole, raw', 'Whole duck', array['duck', 'itik', 'pato'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 337, 11.5, 0, 32.5, 0, 0, 63, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', 1500, 'whole duck'),
  ('Duck breast, raw', 'Duck breast', array['duck breast', 'dibdib ng itik'], 'Poultry', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 201, 19.3, 0, 13.3, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', 200, 'breast');
