-- Batch 7/~13: Rice, grains & noodles (25 items). Same treatment as
-- batches 1-6 — AI-estimated placeholders, honestly tagged
-- source='manual', verification_status='NEEDS_REVIEW', so the "Ground
-- from USDA" tool has real candidates to upgrade against, and any item it
-- can't confidently match still has usable (if approximate) data rather
-- than nulls blocking the meal-nutrition pipeline.
--
-- Rice/grains/flour use state='raw' for the dry-as-bought form (there's no
-- separate "fresh" form being tracked) vs 'cooked' for the prepared form.
-- Noodles/pasta use 'dried' for the dry-as-bought form instead, since
-- that's the more accurate descriptor for how they're sold. Bread
-- (already baked as sold, no raw-dough row tracked) uses 'cooked'.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('White rice, raw', 'White rice', array['bigas', 'white rice', 'rice'], 'Rice', 'Grains & Noodles', 'raw', 'pantry',
   100, 'g', 365, 7.1, 80, 0.7, 0.1, 1.3, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   55, 'kg', 'manual', null, null),
  ('White rice, cooked', 'Cooked white rice', array['kanin', 'cooked rice', 'steamed rice'], 'Rice', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 130, 2.7, 28, 0.3, 0, 0.4, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   20, 'kg', 'manual', null, null),
  ('Brown rice, raw', 'Brown rice', array['brown rice', 'pinawa'], 'Rice', 'Grains & Noodles', 'raw', 'pantry',
   100, 'g', 370, 7.9, 77, 2.9, 0.7, 3.5, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   75, 'kg', 'manual', null, null),
  ('Brown rice, cooked', 'Cooked brown rice', array['cooked brown rice'], 'Rice', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 123, 2.6, 25.6, 1, 0.2, 1.6, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   28, 'kg', 'manual', null, null),
  ('Glutinous rice, raw', 'Glutinous rice', array['malagkit', 'sticky rice', 'glutinous rice'], 'Rice', 'Grains & Noodles', 'raw', 'pantry',
   100, 'g', 370, 7.3, 81.7, 0.6, 0, 2.8, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', null, null),
  ('Glutinous rice, cooked', 'Cooked glutinous rice', array['cooked malagkit', 'cooked sticky rice'], 'Rice', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 130, 2.7, 28.6, 0.2, 0, 0.9, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   26, 'kg', 'manual', null, null),
  ('Fried rice, sinangag', 'Fried rice (sinangag)', array['sinangag', 'garlic fried rice', 'fried rice'], 'Rice', 'Grains & Noodles', 'fried', 'pantry',
   100, 'g', 186, 3, 30, 6, 0.3, 0.5, 300, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   40, 'kg', 'manual', null, null),
  ('Corn kernels, raw', 'Corn kernels', array['mais', 'corn', 'sweet corn'], 'Grain', 'Grains & Noodles', 'raw', 'pantry',
   100, 'g', 86, 3.27, 18.7, 1.35, 6.26, 2, 15, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Corn grits, raw', 'Corn grits', array['corn grits', 'ginataang mais grits'], 'Grain', 'Grains & Noodles', 'raw', 'pantry',
   100, 'g', 370, 8, 79, 1.5, 0.5, 4, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', null, null),
  ('Rolled oats, raw', 'Rolled oats', array['oats', 'rolled oats', 'oatmeal (dry)'], 'Grain', 'Grains & Noodles', 'raw', 'pantry',
   100, 'g', 389, 16.9, 66.3, 6.9, 0, 10.6, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Oatmeal, cooked', 'Cooked oatmeal', array['cooked oatmeal', 'oatmeal porridge'], 'Grain', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 71, 2.5, 12, 1.5, 0.3, 1.7, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Rice noodles, dried', 'Rice noodles (bihon)', array['bihon', 'rice noodles', 'rice vermicelli'], 'Noodles', 'Grains & Noodles', 'dried', 'pantry',
   100, 'g', 364, 6, 83, 0.6, 0.2, 1.6, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Rice noodles, cooked', 'Cooked rice noodles (bihon)', array['cooked bihon', 'cooked rice noodles'], 'Noodles', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 109, 1.8, 25, 0.2, 0.1, 0.9, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   45, 'kg', 'manual', null, null),
  ('Egg noodles, dried', 'Egg noodles (canton)', array['canton', 'miki', 'egg noodles'], 'Noodles', 'Grains & Noodles', 'dried', 'pantry',
   100, 'g', 384, 13, 71, 4.9, 2, 3, 8, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   130, 'kg', 'manual', null, null),
  ('Egg noodles, cooked', 'Cooked egg noodles (canton)', array['cooked canton', 'cooked egg noodles'], 'Noodles', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 138, 4.5, 25, 2, 0.5, 1.2, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', null, null),
  ('Glass noodles, dried', 'Glass noodles (sotanghon)', array['sotanghon', 'glass noodles', 'vermicelli'], 'Noodles', 'Grains & Noodles', 'dried', 'pantry',
   100, 'g', 351, 0.2, 86, 0.1, 0, 0.9, 7, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Glass noodles, cooked', 'Cooked glass noodles (sotanghon)', array['cooked sotanghon', 'cooked glass noodles'], 'Noodles', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 95, 0.1, 23, 0, 0, 0.2, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   55, 'kg', 'manual', null, null),
  ('Spaghetti, dried', 'Spaghetti', array['spaghetti', 'pasta'], 'Noodles', 'Grains & Noodles', 'dried', 'pantry',
   100, 'g', 371, 13, 74.7, 1.5, 2.7, 3.2, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Spaghetti, cooked', 'Cooked spaghetti', array['cooked spaghetti', 'cooked pasta'], 'Noodles', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 158, 5.8, 30.9, 0.9, 0.6, 1.8, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   35, 'kg', 'manual', null, null),
  ('Macaroni, dried', 'Macaroni', array['macaroni', 'elbow macaroni'], 'Noodles', 'Grains & Noodles', 'dried', 'pantry',
   100, 'g', 371, 13, 74.7, 1.5, 2.7, 3.2, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Macaroni, cooked', 'Cooked macaroni', array['cooked macaroni'], 'Noodles', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 158, 5.8, 30.9, 0.9, 0.6, 1.8, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   35, 'kg', 'manual', null, null),
  ('Instant noodles, dried', 'Instant noodles', array['instant noodles', 'instant mami', 'cup noodles'], 'Noodles', 'Grains & Noodles', 'dried', 'pantry',
   100, 'g', 436, 9, 62, 17, 3, 2, 1700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', 60, 'pack'),
  ('Pandesal', 'Pandesal', array['pandesal', 'bread roll'], 'Bread', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 289, 9, 53, 4.5, 6, 2, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', 30, 'piece'),
  ('White bread, sliced', 'White bread', array['tasty bread', 'white bread', 'loaf bread'], 'Bread', 'Grains & Noodles', 'cooked', 'pantry',
   100, 'g', 265, 9, 49, 3.2, 5, 2.7, 490, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   160, 'kg', 'manual', 25, 'slice'),
  ('Rice flour', 'Rice flour', array['rice flour', 'galapong'], 'Grain', 'Grains & Noodles', 'raw', 'pantry',
   100, 'g', 366, 6, 80, 1.4, 0.1, 2.4, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', null, null);
