-- Batch 11/~13: Fruits (40 items). Same treatment as batches 1-10 —
-- AI-estimated placeholders, honestly tagged source='manual',
-- verification_status='NEEDS_REVIEW', so the "Ground from USDA" tool has
-- real candidates to upgrade against, and any item it can't confidently
-- match still has usable (if approximate) data rather than nulls blocking
-- the meal-nutrition pipeline.
--
-- Covers everyday and Filipino-specific fresh fruits, plus common
-- processed/pantry forms (dried mango, canned pineapple/peach/fruit
-- cocktail, raisins, nata de coco) — kept as separate canonical rows from
-- their fresh form since drying/canning/syrup genuinely changes the
-- nutrition profile, same cooking-state-as-identity rule as every prior
-- batch. New food_group='Fruits'. Coconut water uses basis_unit='ml' like
-- the liquid dairy in batch 6.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Banana, lakatan, raw', 'Banana (lakatan)', array['lakatan', 'banana'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 89, 1.1, 22.8, 0.3, 12.2, 2.6, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', 120, 'piece'),
  ('Banana, saba, raw', 'Banana (saba)', array['saba', 'cooking banana', 'plantain'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 120, 1.2, 31.9, 0.3, 14, 2.3, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', 90, 'piece'),
  ('Banana, saba, cooked', 'Cooked banana (saba)', array['boiled saba', 'minatamis na saging'], 'Fruit', 'Fruits', 'cooked', 'main',
   100, 'g', 135, 1.3, 35, 0.3, 16, 2.5, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', null, null),
  ('Mango, ripe, raw', 'Ripe mango', array['mangga', 'ripe mango', 'mango'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 60, 0.8, 15, 0.4, 13.7, 1.6, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 300, 'piece'),
  ('Mango, green, raw', 'Green mango', array['mangga na hilaw', 'green mango', 'unripe mango'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 40, 0.8, 9.4, 0.3, 2, 1.5, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Mango, dried', 'Dried mango', array['dried mango'], 'Fruit', 'Fruits', 'dried', 'pantry',
   100, 'g', 319, 1.9, 78, 0.9, 68, 3, 9, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Papaya, ripe, raw', 'Ripe papaya', array['papaya', 'ripe papaya'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 43, 0.5, 10.8, 0.3, 7.8, 1.7, 8, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', null, null),
  ('Pineapple, raw', 'Pineapple', array['pinya', 'pineapple'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 50, 0.5, 13.1, 0.1, 9.9, 1.4, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', 1000, 'piece'),
  ('Pineapple, canned', 'Canned pineapple', array['canned pineapple', 'pineapple chunks'], 'Fruit', 'Fruits', 'cooked', 'pantry',
   100, 'g', 60, 0.4, 15.5, 0.1, 14, 0.6, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Watermelon, raw', 'Watermelon', array['pakwan', 'watermelon'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 30, 0.6, 7.6, 0.2, 6.2, 0.4, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   40, 'kg', 'manual', 3000, 'piece'),
  ('Melon, raw', 'Melon', array['milon', 'melon', 'cantaloupe'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 34, 0.8, 8.2, 0.2, 7.9, 0.9, 16, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', null, null),
  ('Calamansi, raw', 'Calamansi', array['calamansi', 'philippine lime'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 38, 0.7, 9.7, 0.1, 1.7, 2.8, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', 15, 'piece'),
  ('Dalandan, raw', 'Dalandan (Philippine orange)', array['dalandan', 'philippine orange'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 47, 0.9, 11.8, 0.1, 9.4, 2.4, 0, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', 150, 'piece'),
  ('Pomelo, raw', 'Pomelo (suha)', array['suha', 'pomelo'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 38, 0.8, 9.6, 0.04, 6.9, 1, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', 1200, 'piece'),
  ('Guava, raw', 'Guava (bayabas)', array['bayabas', 'guava'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 68, 2.6, 14.3, 1, 8.9, 5.4, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', null, null),
  ('Guyabano, raw', 'Guyabano (soursop)', array['guyabano', 'soursop'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 66, 1, 16.8, 0.3, 13.5, 3.3, 14, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', 800, 'piece'),
  ('Avocado, raw', 'Avocado', array['avocado'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 160, 2, 8.5, 14.7, 0.7, 6.7, 7, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 200, 'piece'),
  ('Rambutan, raw', 'Rambutan', array['rambutan'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 82, 0.9, 20.9, 0.1, 5.7, 0.9, 11, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Lanzones, raw', 'Lanzones', array['lanzones'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 57, 1, 14, 0.2, 8, 2, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Mangosteen, raw', 'Mangosteen', array['mangosteen'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 73, 0.4, 17.9, 0.6, 16, 1.8, 7, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Durian, raw', 'Durian', array['durian'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 147, 1.5, 27.1, 5.3, 3, 3.8, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', 2000, 'piece'),
  ('Jackfruit, ripe, raw', 'Ripe jackfruit', array['langka', 'ripe jackfruit'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 95, 1.7, 23.2, 0.6, 19.1, 1.5, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Star apple, raw', 'Star apple (kaimito)', array['kaimito', 'star apple'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 67, 0.7, 14.6, 1.7, 0, 3.4, 8, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Santol, raw', 'Santol', array['santol'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 80, 0.8, 20.4, 0.3, 0, 2.5, 8, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Chico, raw', 'Chico (sapodilla)', array['chico', 'sapodilla'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 83, 0.4, 20, 1.1, 14, 5.3, 12, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Atis, raw', 'Atis (sugar apple)', array['atis', 'sugar apple'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 94, 2.1, 23.6, 0.3, 0, 4.4, 9, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Tamarind, raw', 'Tamarind (sampaloc)', array['sampaloc', 'tamarind'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 239, 2.8, 62.5, 0.6, 38, 5.1, 28, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Dragon fruit, raw', 'Dragon fruit', array['dragon fruit', 'pitaya'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 60, 1.2, 13, 0.4, 8, 3, 39, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Coconut, young, raw', 'Young coconut (buko)', array['buko', 'young coconut'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 28, 0.7, 3.9, 1.4, 0, 1.1, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   50, 'kg', 'manual', 1500, 'piece'),
  ('Coconut, mature, raw', 'Mature coconut', array['niyog', 'mature coconut'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 354, 3.3, 15.2, 33.5, 6.2, 9, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Coconut water', 'Coconut water (buko juice)', array['buko juice', 'coconut water'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'ml', 19, 0.7, 3.7, 0.2, 2.6, 1.1, 105, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'L', 'manual', null, null),
  ('Apple, raw', 'Apple', array['mansanas', 'apple'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 52, 0.3, 13.8, 0.2, 10.4, 2.4, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', 150, 'piece'),
  ('Orange, raw', 'Orange', array['orange', 'dalanghita'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 47, 0.9, 11.8, 0.1, 9.4, 2.4, 0, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', 150, 'piece'),
  ('Grapes, raw', 'Grapes', array['ubas', 'grapes'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 69, 0.7, 18.1, 0.2, 15.5, 0.9, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Strawberry, raw', 'Strawberry', array['strawberry'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 32, 0.7, 7.7, 0.3, 4.9, 2, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Pear, raw', 'Pear', array['peras', 'pear'], 'Fruit', 'Fruits', 'raw', 'main',
   100, 'g', 57, 0.4, 15.2, 0.1, 9.8, 3.1, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', 170, 'piece'),
  ('Peach, canned', 'Canned peach', array['canned peach', 'peaches'], 'Fruit', 'Fruits', 'cooked', 'pantry',
   100, 'g', 68, 0.5, 17.7, 0.1, 17, 1, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Fruit cocktail, canned', 'Fruit cocktail', array['fruit cocktail', 'fruit salad mix'], 'Fruit', 'Fruits', 'cooked', 'pantry',
   100, 'g', 76, 0.4, 19.6, 0.05, 17, 1.1, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   130, 'kg', 'manual', null, null),
  ('Raisins', 'Raisins', array['raisins'], 'Fruit', 'Fruits', 'dried', 'pantry',
   100, 'g', 299, 3.1, 79.2, 0.5, 59, 3.7, 11, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   350, 'kg', 'manual', null, null),
  ('Nata de coco', 'Nata de coco', array['nata de coco', 'coconut gel'], 'Fruit', 'Fruits', 'cooked', 'pantry',
   100, 'g', 146, 0, 36, 0, 34, 1.5, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null);
