-- Batch 12/~13: Aromatics, herbs & spices (40 items). Same treatment as
-- batches 1-11 — AI-estimated placeholders, honestly tagged
-- source='manual', verification_status='NEEDS_REVIEW', so the "Ground
-- from USDA" tool has real candidates to upgrade against, and any item it
-- can't confidently match still has usable (if approximate) data rather
-- than nulls blocking the meal-nutrition pipeline.
--
-- KNOWN OVERLAP, accepted deliberately for now (dedupe later along with
-- the canonical_name uniqueness question): the original batch-1 seed
-- already has generic 'Garlic' and 'Onion' rows (no raw/fried or
-- red/white split) tagged food_group='Vegetables'. This batch adds
-- 'Garlic, raw' / 'Garlic, fried' / 'Onion, red, raw' / 'Onion, white,
-- raw' as more specific variants under food_group='Herbs & Spices'
-- instead — different canonical_name strings, so no DB conflict, but real
-- conceptual duplication until cleaned up.
--
-- food_group='Herbs & Spices' reuses the bucket 'Bay leaf' and
-- 'Black pepper, ground' already established in batch 1, rather than
-- introducing a differently-named one.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Garlic, raw', 'Garlic', array['bawang', 'garlic cloves'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 149, 6.4, 33.1, 0.5, 1, 2.1, 17, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', 5, 'clove'),
  ('Garlic, fried', 'Fried garlic (toasted garlic bits)', array['toasted garlic', 'garlic chips', 'fried garlic'], 'Aromatics', 'Herbs & Spices', 'fried', 'pantry',
   100, 'g', 450, 12, 45, 25, 2, 3, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Onion, red, raw', 'Red onion', array['pulang sibuyas', 'red onion'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 40, 1.1, 9.3, 0.1, 4.2, 1.7, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', 110, 'piece'),
  ('Onion, white, raw', 'White onion', array['puting sibuyas', 'white onion', 'yellow onion'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 40, 1.1, 9.3, 0.1, 4.2, 1.7, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', 110, 'piece'),
  ('Onion, spring, raw', 'Spring onion (scallion)', array['sibuyas na mura', 'scallion', 'green onion', 'spring onion'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 32, 1.8, 7.3, 0.2, 2.3, 2.6, 16, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', 15, 'stalk'),
  ('Shallots, raw', 'Shallots', array['sibuyas tagalog', 'shallots'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 72, 2.5, 16.8, 0.1, 7.9, 3.2, 12, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Shallots, fried', 'Fried shallots', array['fried shallots', 'crispy shallots'], 'Aromatics', 'Herbs & Spices', 'fried', 'pantry',
   100, 'g', 490, 5, 45, 32, 8, 3, 15, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   450, 'kg', 'manual', null, null),
  ('Ginger, raw', 'Ginger', array['luya', 'ginger'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 80, 1.8, 17.8, 0.8, 1.7, 2, 13, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Ginger, ground', 'Ground ginger', array['ground ginger', 'ginger powder'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 335, 9, 71.6, 4.2, 3.4, 14.1, 27, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   600, 'kg', 'manual', null, null),
  ('Turmeric, raw', 'Turmeric', array['luyang dilaw', 'turmeric'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 312, 7.8, 67.1, 3.25, 3.2, 21, 27, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Turmeric, ground', 'Ground turmeric', array['ground turmeric', 'turmeric powder'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 354, 7.8, 65, 10, 3.2, 21, 38, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null),
  ('Galangal, raw', 'Galangal', array['langkauas', 'galangal'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 71, 1.5, 15.5, 0.9, 0, 2.5, 15, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Lemongrass, raw', 'Lemongrass', array['tanglad', 'lemongrass'], 'Aromatics', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 99, 1.8, 25.3, 0.5, 0, 0, 6, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', null, null),
  ('Basil, raw', 'Basil (balanoy)', array['balanoy', 'basil'], 'Herb', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 23, 3.2, 2.7, 0.6, 0.3, 1.6, 4, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Cilantro, raw', 'Cilantro (wansoy)', array['wansoy', 'cilantro', 'coriander leaves'], 'Herb', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 23, 2.1, 3.7, 0.5, 0.9, 2.8, 46, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Parsley, raw', 'Parsley', array['parsley'], 'Herb', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 36, 3, 6.3, 0.8, 0.9, 3.3, 56, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Mint, raw', 'Mint (yerba buena)', array['yerba buena', 'mint'], 'Herb', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 70, 3.8, 14.9, 0.9, 0, 8, 31, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Pandan leaves, raw', 'Pandan leaves', array['pandan', 'screwpine leaves'], 'Herb', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 39, 1, 9, 0.2, 0, 1.5, 10, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Oregano, dried', 'Dried oregano', array['oregano', 'dried oregano'], 'Herb', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 265, 9, 68.9, 4.3, 4.1, 42.5, 25, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   1200, 'kg', 'manual', null, null),
  ('Thyme, dried', 'Dried thyme', array['thyme', 'dried thyme'], 'Herb', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 276, 9.1, 63.9, 7.4, 1.7, 37, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   1500, 'kg', 'manual', null, null),
  ('Rosemary, dried', 'Dried rosemary', array['rosemary', 'dried rosemary'], 'Herb', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 331, 4.9, 64.1, 15.2, 0, 42.6, 50, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   1500, 'kg', 'manual', null, null),
  ('Dill, raw', 'Dill', array['dill'], 'Herb', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 43, 3.5, 7, 1.1, 0, 2.1, 61, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Black peppercorns, whole', 'Black peppercorns', array['whole black pepper', 'black peppercorns'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 251, 10.4, 63.9, 3.3, 0.6, 25.3, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   900, 'kg', 'manual', null, null),
  ('White pepper, ground', 'Ground white pepper', array['white pepper', 'ground white pepper'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 296, 10.4, 68.6, 2.1, 0.5, 26.2, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   1200, 'kg', 'manual', null, null),
  ('Paprika, ground', 'Ground paprika', array['paprika'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 282, 14.1, 54, 12.9, 10.3, 34.9, 68, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   1000, 'kg', 'manual', null, null),
  ('Cayenne pepper, ground', 'Ground cayenne pepper', array['cayenne pepper', 'ground cayenne'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 318, 12, 56.6, 11, 10.3, 27.2, 30, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   1000, 'kg', 'manual', null, null),
  ('Cumin, ground', 'Ground cumin', array['cumin', 'ground cumin'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 375, 17.8, 44.2, 22.3, 2.3, 10.5, 168, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   1200, 'kg', 'manual', null, null),
  ('Coriander seed, ground', 'Ground coriander seed', array['coriander seed', 'ground coriander'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 298, 12.4, 55, 12.5, 0, 41.9, 35, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   900, 'kg', 'manual', null, null),
  ('Star anise, whole', 'Star anise', array['star anise'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 337, 17.6, 50, 15.9, 0, 14.6, 16, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   2000, 'kg', 'manual', null, null),
  ('Cinnamon, ground', 'Ground cinnamon (kalingag)', array['kalingag', 'ground cinnamon'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 247, 4, 80.6, 1.2, 2.2, 53.1, 10, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   700, 'kg', 'manual', null, null),
  ('Cinnamon stick, whole', 'Cinnamon stick', array['cinnamon stick'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 247, 4, 80.6, 1.2, 2.2, 53.1, 10, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   700, 'kg', 'manual', 5, 'stick'),
  ('Cloves, whole', 'Cloves', array['clove', 'cloves'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 274, 6, 65.5, 6.2, 2.4, 33.9, 277, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   2500, 'kg', 'manual', null, null),
  ('Nutmeg, ground', 'Ground nutmeg', array['nutmeg', 'ground nutmeg'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 525, 5.8, 49.3, 36.3, 28.5, 20.8, 16, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   3000, 'kg', 'manual', null, null),
  ('Annatto seeds, whole', 'Annatto seeds (achuete)', array['achuete', 'annatto seeds', 'atsuete'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 318, 12, 60, 10, 0, 30, 20, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   600, 'kg', 'manual', null, null),
  ('Chili flakes, dried', 'Dried chili flakes', array['chili flakes', 'red pepper flakes'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 321, 12, 57, 11, 10, 27, 30, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   900, 'kg', 'manual', null, null),
  ('Sesame seeds, raw', 'Sesame seeds (linga)', array['linga', 'sesame seeds'], 'Spice', 'Herbs & Spices', 'raw', 'pantry',
   100, 'g', 573, 17.7, 23.4, 49.7, 0.3, 11.8, 11, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null),
  ('Fennel seeds, whole', 'Fennel seeds', array['fennel seeds'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 345, 15.8, 52.3, 14.9, 0, 39.8, 88, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   800, 'kg', 'manual', null, null),
  ('Cardamom, whole', 'Cardamom pods', array['cardamom', 'cardamom pods'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 311, 10.8, 68.5, 6.7, 0, 28, 18, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   4000, 'kg', 'manual', null, null),
  ('Mustard seeds, whole', 'Mustard seeds', array['mustard seeds'], 'Spice', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 508, 26.1, 28.1, 36.2, 6.8, 12.2, 13, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null),
  ('Vetsin', 'Vetsin (MSG)', array['msg', 'monosodium glutamate', 'vetsin', 'ajinomoto'], 'Seasoning', 'Herbs & Spices', 'dried', 'pantry',
   100, 'g', 0, 0, 0, 0, 0, 0, 12000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null);
