-- Batch 15/~16: Pantry staples (40 items). Same treatment as prior
-- batches — AI-estimated placeholders, honestly tagged source='manual',
-- verification_status='NEEDS_REVIEW', so the "Ground from USDA" tool has
-- real candidates to upgrade against, and any item it can't confidently
-- match still has usable (if approximate) data rather than nulls
-- blocking the meal-nutrition pipeline.
--
-- New food_group='Pantry Staples' for baking ingredients, sweeteners,
-- canned goods not covered by more specific earlier batches, crackers/
-- snacks, and beverage/baking mixes. state='dried' for genuinely
-- dehydrated powders (flour, cornstarch, leavening, cocoa, sugars,
-- crackers, instant coffee/drink mixes); 'cooked' for canned/heat-
-- processed goods; null for liquids with no clean state fit (vanilla
-- extract, food coloring, corn syrup, molasses, cooking wine).
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('All-purpose flour', 'All-purpose flour', array['flour', 'all-purpose flour', 'harina'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 364, 10.3, 76.3, 1, 0.3, 2.7, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   60, 'kg', 'manual', null, null),
  ('Bread flour', 'Bread flour', array['bread flour', 'high-gluten flour'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 361, 12.6, 72.5, 1.7, 0.3, 2.4, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', null, null),
  ('Cake flour', 'Cake flour', array['cake flour'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 362, 8, 78, 0.9, 0.3, 1.6, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', null, null),
  ('Cornstarch', 'Cornstarch', array['cornstarch', 'corn starch'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 381, 0.3, 91.3, 0.1, 0, 0.9, 9, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Baking powder', 'Baking powder', array['baking powder'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 53, 0, 13.3, 0, 0, 0, 10600, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Baking soda', 'Baking soda', array['baking soda', 'sodium bicarbonate'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 0, 0, 0, 0, 0, 0, 27360, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Yeast, active dry', 'Active dry yeast', array['yeast', 'active dry yeast'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 325, 40, 41, 7.6, 0, 26.9, 51, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   800, 'kg', 'manual', null, null),
  ('Gelatin, powdered', 'Powdered gelatin', array['gelatin', 'unflavored gelatin'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 335, 85.6, 0, 0.1, 0, 0, 127, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   600, 'kg', 'manual', null, null),
  ('Cocoa powder', 'Cocoa powder', array['cocoa powder', 'cacao powder'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 228, 19.6, 57.9, 13.7, 1.8, 37, 21, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null),
  ('Chocolate, dark, baking', 'Dark baking chocolate (tablea)', array['tablea', 'baking chocolate', 'dark chocolate'], 'Baking', 'Pantry Staples', 'raw', 'pantry',
   100, 'g', 546, 7.9, 45.9, 42.6, 24, 11, 24, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Vanilla extract', 'Vanilla extract', array['vanilla extract', 'vanilla'], 'Baking', 'Pantry Staples', null, 'pantry',
   100, 'ml', 288, 0.1, 12.7, 0.1, 12.7, 0, 9, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   800, 'L', 'manual', null, null),
  ('Food coloring', 'Food coloring', array['food coloring', 'food color'], 'Baking', 'Pantry Staples', null, 'pantry',
   100, 'ml', 0, 0, 0, 0, 0, 0, 5, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'L', 'manual', null, null),
  ('Sugar, white', 'White sugar', array['asukal', 'white sugar', 'granulated sugar'], 'Sweetener', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 387, 0, 100, 0, 100, 0, 0, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   70, 'kg', 'manual', null, null),
  ('Sugar, brown', 'Brown sugar', array['brown sugar'], 'Sweetener', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 380, 0.1, 98.1, 0, 97, 0, 28, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   75, 'kg', 'manual', null, null),
  ('Sugar, muscovado', 'Muscovado sugar', array['muscovado', 'panutsa', 'muscovado sugar'], 'Sweetener', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 375, 0.2, 96, 0, 90, 0, 39, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Sugar, powdered', 'Powdered sugar', array['powdered sugar', 'confectioners sugar', 'icing sugar'], 'Sweetener', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 389, 0, 99.8, 0, 99.8, 0, 2, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Corn syrup', 'Corn syrup', array['corn syrup'], 'Sweetener', 'Pantry Staples', null, 'pantry',
   100, 'ml', 282, 0, 76.4, 0.1, 40, 0, 27, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Molasses', 'Molasses', array['molasses'], 'Sweetener', 'Pantry Staples', null, 'pantry',
   100, 'ml', 290, 0, 74.7, 0.1, 74.7, 0, 37, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'L', 'manual', null, null),
  ('Canned mushrooms', 'Canned mushrooms', array['canned mushrooms'], 'Canned Goods', 'Pantry Staples', 'cooked', 'pantry',
   100, 'g', 19, 1.9, 2.9, 0.2, 0.9, 1.4, 332, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Canned green peas', 'Canned green peas', array['canned green peas'], 'Canned Goods', 'Pantry Staples', 'cooked', 'pantry',
   100, 'g', 66, 3.5, 12.1, 0.3, 3, 4, 320, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Canned corn kernels', 'Canned corn kernels', array['canned corn', 'canned sweet corn'], 'Canned Goods', 'Pantry Staples', 'cooked', 'pantry',
   100, 'g', 66, 2, 15, 0.6, 3, 1.7, 270, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   80, 'kg', 'manual', null, null),
  ('Canned luncheon meat', 'Canned luncheon meat', array['spam', 'luncheon meat', 'canned luncheon meat'], 'Canned Goods', 'Pantry Staples', 'cooked', 'pantry',
   100, 'g', 310, 13, 3, 27, 0, 0, 1400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Vienna sausage, canned', 'Canned Vienna sausage', array['vienna sausage', 'canned vienna sausage'], 'Canned Goods', 'Pantry Staples', 'cooked', 'pantry',
   100, 'g', 230, 11, 3, 20, 0, 0, 850, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Meatloaf, canned', 'Canned meatloaf', array['canned meatloaf'], 'Canned Goods', 'Pantry Staples', 'cooked', 'pantry',
   100, 'g', 220, 14, 6, 15, 1, 0, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Canned tomatoes, whole', 'Canned whole tomatoes', array['canned tomatoes', 'canned whole tomatoes'], 'Canned Goods', 'Pantry Staples', 'cooked', 'pantry',
   100, 'g', 18, 0.9, 4.1, 0.1, 2.6, 1.1, 130, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null),
  ('Crackers, saltine', 'Saltine crackers', array['saltine crackers', 'crackers'], 'Snacks', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 421, 9.5, 74, 10.6, 3, 2.6, 1000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Biscuits, Marie', 'Marie biscuits', array['marie biscuits', 'marie crackers'], 'Snacks', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 440, 7.5, 75, 12, 20, 2, 350, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Crackers, graham', 'Graham crackers', array['graham crackers'], 'Snacks', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 421, 7, 73, 11, 24, 3, 500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Bread crumbs', 'Bread crumbs', array['bread crumbs', 'panko'], 'Baking', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 395, 13, 72, 5, 6, 4.5, 700, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   120, 'kg', 'manual', null, null),
  ('Cornflakes', 'Cornflakes', array['cornflakes', 'corn flakes'], 'Snacks', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 357, 7.5, 84, 0.9, 8, 3, 660, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Instant coffee', 'Instant coffee', array['instant coffee', 'coffee powder'], 'Beverage Mix', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 253, 12.2, 43.3, 0.5, 0, 30, 33, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   700, 'kg', 'manual', null, null),
  ('Instant chocolate drink mix', 'Instant chocolate drink mix', array['milo', 'chocolate drink mix', 'instant chocolate mix'], 'Beverage Mix', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 394, 8, 78, 5, 55, 3, 200, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', null, null),
  ('Powdered juice drink mix', 'Powdered juice drink mix', array['tang', 'powdered juice', 'juice drink mix'], 'Beverage Mix', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 380, 0, 95, 0, 90, 0, 40, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Gravy mix, powdered', 'Powdered gravy mix', array['gravy mix', 'gravy powder'], 'Baking Mix', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 350, 8, 65, 6, 5, 2, 8000, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Pancake mix, powdered', 'Powdered pancake mix', array['pancake mix'], 'Baking Mix', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 360, 8, 75, 3, 15, 2, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null),
  ('Cake mix, powdered', 'Powdered cake mix', array['cake mix'], 'Baking Mix', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 380, 4, 80, 5, 45, 1, 500, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   250, 'kg', 'manual', null, null),
  ('Cooking wine, Chinese', 'Chinese cooking wine', array['shaoxing wine', 'chinese cooking wine', 'cooking wine'], 'Baking', 'Pantry Staples', null, 'pantry',
   100, 'ml', 110, 0.3, 5, 0, 1, 0, 300, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'L', 'manual', null, null),
  ('Tapioca pearls', 'Tapioca pearls (sago)', array['sago', 'tapioca pearls'], 'Starch', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 358, 0.2, 88.7, 0.02, 3, 0.9, 1, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Gulaman powder', 'Gulaman powder (agar-agar)', array['gulaman', 'agar-agar', 'agar powder'], 'Starch', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 306, 6.2, 80.9, 0.3, 0, 80.9, 58, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Cassava flour', 'Cassava flour', array['cassava flour', 'tapioca flour'], 'Starch', 'Pantry Staples', 'dried', 'pantry',
   100, 'g', 330, 1.5, 81, 0.3, 2, 3.7, 3, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   90, 'kg', 'manual', null, null);
