-- Batch 3/~13: Pork (25 items). Same treatment as batches 1-2 — AI-estimated
-- placeholders, honestly tagged source='manual', verification_status='NEEDS_REVIEW',
-- so the "Ground from USDA" tool has real candidates to upgrade against, and any
-- item it can't confidently match still has usable (if approximate) data rather
-- than nulls blocking the meal-nutrition pipeline.
--
-- Covers raw cuts, organs, and Filipino-specific cured/cooked pork products
-- (tocino, longganisa, tapa, sisig, chicharon, lechon kawali) — these are
-- kept as their own canonical rows rather than "pork + recipe instructions"
-- since curing/frying genuinely changes the nutrition profile, consistent
-- with the cooking-state-as-identity rule already applied to poultry.
insert into public.ingredients (
  canonical_name, display_name, aliases, category, food_group, state, role,
  basis_amount, basis_unit, calories, protein, carbohydrates, fat, sugar, fiber, sodium,
  source, source_description, verification_status,
  estimated_price, estimated_price_unit, price_source,
  grams_per_piece, piece_label
) values
  ('Pork belly, raw', 'Pork belly (liempo)', array['pork belly', 'liempo'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 518, 9.3, 0, 53, 0, 0, 54, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   380, 'kg', 'manual', null, null),
  ('Pork shoulder, raw', 'Pork shoulder (kasim)', array['pork shoulder', 'kasim'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 269, 17.2, 0, 21.8, 0, 0, 58, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   320, 'kg', 'manual', null, null),
  ('Pork ham, raw', 'Pork ham (pigue)', array['pork ham', 'pigue', 'fresh ham'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 242, 19.9, 0, 17.4, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   330, 'kg', 'manual', null, null),
  ('Pork loin, raw', 'Pork loin', array['pork loin', 'lomo ng baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 143, 21.5, 0, 5.7, 0, 0, 55, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   340, 'kg', 'manual', null, null),
  ('Pork spare ribs, raw', 'Pork spare ribs', array['pork ribs', 'spare ribs', 'tadyang ng baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 277, 17.9, 0, 22.4, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   320, 'kg', 'manual', null, null),
  ('Ground pork, raw', 'Ground pork', array['ground pork', 'giniling na baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 263, 16.9, 0, 21.2, 0, 0, 58, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   300, 'kg', 'manual', null, null),
  ('Pork liver, raw', 'Pork liver', array['pork liver', 'atay ng baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 134, 21.4, 3.7, 3.7, 0, 0, 87, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', null, null),
  ('Pork intestines, raw', 'Pork intestines', array['pork intestines', 'bituka ng baboy', 'isaw'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 227, 13.4, 0, 18.9, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Pork blood, raw', 'Pork blood', array['pork blood', 'dugo ng baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 65, 11.7, 0, 1.5, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   100, 'kg', 'manual', null, null),
  ('Pork ear, raw', 'Pork ear', array['pork ear', 'tenga ng baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 234, 21.6, 0, 15.8, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Pork feet, raw', 'Pork feet (pata)', array['pork feet', 'pata', 'pig trotters'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 259, 19.6, 0, 19.6, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   220, 'kg', 'manual', null, null),
  ('Pork skin, raw', 'Pork skin', array['pork skin', 'balat ng baboy', 'pork rind raw'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 304, 27, 1.4, 21, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Pork kidney, raw', 'Pork kidney', array['pork kidney', 'bato ng baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 108, 17.3, 0, 3.6, 0, 0, 178, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   180, 'kg', 'manual', null, null),
  ('Pork tail, raw', 'Pork tail', array['pork tail', 'buntot ng baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 396, 15, 0, 37, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Pork snout, raw', 'Pork snout', array['pork snout', 'nguso ng baboy'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 234, 18, 0, 17, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   150, 'kg', 'manual', null, null),
  ('Pork belly, cooked', 'Cooked pork belly', array['cooked pork belly', 'lutong liempo'], 'Pork', 'Meat & Poultry', 'cooked', 'main',
   100, 'g', 636, 12.8, 0, 65.3, 0, 0, 60, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   420, 'kg', 'manual', null, null),
  ('Lechon kawali', 'Lechon kawali (fried pork belly)', array['lechon kawali', 'fried pork belly'], 'Pork', 'Meat & Poultry', 'fried', 'main',
   100, 'g', 590, 14, 2, 58, 0, 0.2, 400, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   450, 'kg', 'manual', null, null),
  ('Chicharon', 'Chicharon (fried pork rind)', array['chicharon', 'pork cracklings', 'pork rind fried'], 'Pork', 'Meat & Poultry', 'fried', 'main',
   100, 'g', 544, 61, 0, 32, 0, 0, 1100, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   500, 'kg', 'manual', null, null),
  ('Pork tocino', 'Pork tocino', array['tocino', 'pork tocino', 'cured sweet pork'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 240, 15, 12, 15, 9, 0, 900, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   280, 'kg', 'manual', null, null),
  ('Pork longganisa', 'Pork longganisa', array['longganisa', 'longanisa', 'filipino sausage'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 300, 14, 6, 24, 3, 0, 850, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   260, 'kg', 'manual', 30, 'link'),
  ('Pork tapa', 'Pork tapa', array['tapa', 'pork tapa', 'cured beef-style pork'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 250, 20, 5, 16, 3, 0, 750, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   320, 'kg', 'manual', null, null),
  ('Bacon, pork', 'Pork bacon', array['bacon', 'pork bacon'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 541, 37, 1.4, 42, 0, 0, 1717, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   450, 'kg', 'manual', null, null),
  ('Sisig, cooked', 'Pork sisig', array['sisig', 'pork sisig'], 'Pork', 'Meat & Poultry', 'cooked', 'main',
   100, 'g', 280, 18, 3, 21, 0, 0, 650, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   400, 'kg', 'manual', null, null),
  ('Lechon, roasted pork belly', 'Lechon (roasted pork)', array['lechon', 'whole roasted pig', 'lechon baboy'], 'Pork', 'Meat & Poultry', 'cooked', 'main',
   100, 'g', 480, 22, 0, 42, 0, 0, 350, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   600, 'kg', 'manual', null, null),
  ('Pork hock, raw', 'Pork hock', array['pork hock', 'pata ng baboy', 'hocks'], 'Pork', 'Meat & Poultry', 'raw', 'main',
   100, 'g', 280, 18, 0, 22.5, 0, 0, 65, 'manual', 'AI-estimated placeholder, pending FNRI/USDA grounding', 'NEEDS_REVIEW',
   200, 'kg', 'manual', null, null);
