// "Covered markets" from the footer of DA's Daily Price Index PDF (NCR),
// as printed on Oct 8, 2026. Update if DA's list changes.
export const NCR_MARKETS = [
  "Agora Public Market",
  "Alabang Central Market (Muntinlupa)",
  "Balintawak Cloverleaf Market",
  "Bicutan Market",
  "Cartimar Market",
  "Commonwealth Market",
  "Dagonoy Market",
  "Farmers Market",
  "Grace Marketplace (Pateros)",
  "Hulong Duhat Public Market",
  "KLMV New Karuhaatan Market",
  "La Huerta Public Market",
  "Malabon Central Market",
  "Mandaluyong Public Market I",
  "Mandaluyong Public Market II",
  "Marikina Public Market",
  "Maypajo Market",
  "Mega Q-Mart",
  "Muñoz Market",
  "Murphy Public Market",
  "Mutya ng Pasig Mega Market",
  "Navotas Agora Complex",
  "New Las Piñas City Public Market",
  "New Marulas Public Market",
  "New Parang Market",
  "North Diversion Market",
  "Paco Market",
  "Pasay Public Market",
  "Pritil Market",
  "Poblacion Public Market",
  "Quinta Market",
  "Suki Market Moonwalk",
  "San Andres Market",
  "Taguig People’s Market",
  "Trabajo Market",
];

export const DA_PRICE_PAGE = "https://www.da.gov.ph/price-monitoring/";
